## PROYECTO 

In [13]:
#echo "# proyecto_1" >> README.md
#git init
#git add README.md
#git commit -m "first commit"
#git branch -M main
#git remote add origin https://github.com/jrspm/proyecto_1.git
#git push -u origin main

#git remote add origin https://github.com/jrspm/proyecto_1.git
#git branch -M main
#git push -u origin main



#usar para actualizar el proyecto
#git commit -m "nombre_actualizacion"
#git push -u origin main


import numpy as np

import pandas as pd

import random

lista_1=["PRECIO",
    "CALIDAD_MATERIAL",
    "AREA_PISO",
    "TOTAL_HABITACIONES",
    "AÑO_CONSTRUCCION",
    "FRENTE"]

#print(lista_1)

class Datos_Proyecto:

    def __init__(self, nombre_archivo,lista_columnas):

        self.array_total=np.load(nombre_archivo)
        self.lista_columnas_1=lista_columnas

        rows, columns = self.array_total.shape

        self.cantidad_filas=rows

        self.cantidad_filas_porcentaje=0



    def funcion_1(self,porcentaje_reducir):

        if porcentaje_reducir<1 and porcentaje_reducir>0:

            self.cantidad_filas_porcentaje=(self.cantidad_filas)*porcentaje_reducir

        else:

            print("Valor incorrecto")

        return self.array_total


datos_1=Datos_Proyecto("proyecto_training_data.npy",lista_1)


array_1=datos_1.funcion_1(0.2)

print(array_1)


[[2.08500e+05 7.00000e+00 8.56000e+02 8.00000e+00 2.00300e+03 6.50000e+01]
 [1.81500e+05 6.00000e+00 1.26200e+03 6.00000e+00 1.97600e+03 8.00000e+01]
 [2.23500e+05 7.00000e+00 9.20000e+02 6.00000e+00 2.00100e+03 6.80000e+01]
 ...
 [2.66500e+05 7.00000e+00 1.18800e+03 9.00000e+00 1.94100e+03 6.60000e+01]
 [1.42125e+05 5.00000e+00 1.07800e+03 5.00000e+00 1.95000e+03 6.80000e+01]
 [1.47500e+05 5.00000e+00 1.25600e+03 6.00000e+00 1.96500e+03 7.50000e+01]]
